version: "3.9"
services:
  ethereum-fetcher:
    image: ethereum-fetcher
    build:
      context: .
      dockerfile: ./fetcher/Dockerfile
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:pwd@db:5432/postgres
    networks:
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped

  contract-listener:
    image: contract-listener
    build:
      context: .
      dockerfile: ./listener/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:pwd@db:5432/postgres
    networks:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=db
    networks:
      - backend
    ports:
      - 5432:5432

volumes:
  pgdata:

networks:
  backend:
