version: "3.9"
services:
  ethereum-fetcher:
    image: ethereum-fetcher
    build:
      context: .
      dockerfile: ./fetcher/Dockerfile
    init: true
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file:
      - ./.env

  contract-listener:
    image: contract-listener
    build:
      context: .
      dockerfile: ./listener/Dockerfile
    depends_on:
      - db
    networks:
      - backend
    restart: unless-stopped
    env_file:
      - ./.env

  db:
    image: postgres:16.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432
    env_file:
      - ./.env

volumes:
  pgdata:

networks:
  backend:
